# Generated by Django 4.2.11 on 2026-04-17 16:52

import apps.tests.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_date",
                    models.DateField(blank=True, null=True, verbose_name="测试日期"),
                ),
                (
                    "instrument",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="测试仪器"
                    ),
                ),
                (
                    "tester",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="测试人员"
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储结构化的测试数据",
                        verbose_name="结构化数据",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_data",
                        to="samples.sample",
                        verbose_name="所属样品",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试数据",
                "verbose_name_plural": "测试数据",
                "db_table": "test_data",
                "ordering": ["-test_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="测试类型名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="测试类型描述"),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_types",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试类型",
                "verbose_name_plural": "测试类型",
                "db_table": "test_types",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="TestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "saved_filename",
                    models.CharField(max_length=255, verbose_name="保存后的文件名"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to=apps.tests.models.test_file_upload_path,
                        verbose_name="文件路径",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小（字节）"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "test_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="tests.testdata",
                        verbose_name="所属测试数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试文件",
                "verbose_name_plural": "测试文件",
                "db_table": "test_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="testdata",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_data",
                to="tests.testtype",
                verbose_name="测试类型",
            ),
        ),
        migrations.AddConstraint(
            model_name="testtype",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_test_type"
            ),
        ),
    ]
