# Generated by Django 4.2.11 on 2026-04-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProcessingAlgorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="算法名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="算法描述"),
                ),
                (
                    "script",
                    models.TextField(
                        help_text="用于处理数据并生成图表的Python代码", verbose_name="Python脚本"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithms",
                        to="tests.testtype",
                        verbose_name="测试类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据处理算法",
                "verbose_name_plural": "数据处理算法",
                "db_table": "data_processing_algorithms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="dataprocessingalgorithm",
            constraint=models.UniqueConstraint(
                fields=("test_type", "name"), name="unique_test_type_algorithm"
            ),
        ),
    ]
