# Generated by Django 4.2.11 on 2026-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprocessingalgorithm",
            name="script",
            field=models.TextField(
                help_text="用于处理数据并输出JSON格式画图数据的Python代码", verbose_name="Python脚本"
            ),
        ),
        migrations.CreateModel(
            name="PlotData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimensions",
                    models.IntegerField(help_text="2表示二维图，3表示三维图", verbose_name="数据维度"),
                ),
                (
                    "columns",
                    models.JSONField(
                        help_text='如["X", "Y"]或["X", "Y", "Z"]', verbose_name="数据列名"
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="二维数组格式的画图数据", verbose_name="处理后的数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plot_data",
                        to="analysis.dataprocessingalgorithm",
                        verbose_name="使用的算法",
                    ),
                ),
                (
                    "test_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_data",
                        to="tests.testdata",
                        verbose_name="实验数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "画图数据",
                "verbose_name_plural": "画图数据",
                "db_table": "plot_data",
                "ordering": ["-created_at"],
            },
        ),
    ]
