# Generated by Django 4.2.11 on 2026-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_alter_dataprocessingalgorithm_script_plotdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotdata",
            name="series",
            field=models.JSONField(
                default=list,
                help_text='如[{"name": "实部", "data": [[1,2],[3,4]]}]',
                verbose_name="数据系列",
            ),
        ),
        migrations.AddField(
            model_name="plotdata",
            name="x_column",
            field=models.CharField(
                default="", help_text='X轴的列名，如"频率"', max_length=200, verbose_name="X轴列名"
            ),
        ),
        migrations.AlterField(
            model_name="plotdata",
            name="columns",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="旧格式兼容字段",
                null=True,
                verbose_name="数据列名(旧格式)",
            ),
        ),
        migrations.AlterField(
            model_name="plotdata",
            name="data",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="旧格式兼容字段",
                null=True,
                verbose_name="处理后的数据(旧格式)",
            ),
        ),
    ]
