# Generated by Django 4.2.11 on 2026-04-25 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0003_plotdata_series_plotdata_x_column_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="布局名称")),
                (
                    "layout_data",
                    models.JSONField(
                        default=dict, help_text="包含卡片位置、大小、图表配置等", verbose_name="布局数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvas_layouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "画布布局",
                "verbose_name_plural": "画布布局",
                "db_table": "canvas_layouts",
                "ordering": ["-updated_at"],
            },
        ),
    ]
