# Generated by Django 4.2.11 on 2026-04-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_canvaslayout"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotdata",
            name="x_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text='X轴的单位，如"Hz"',
                max_length=50,
                verbose_name="X轴单位",
            ),
        ),
        migrations.AddField(
            model_name="plotdata",
            name="y_column",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Y轴的列名，如"磁导率"',
                max_length=200,
                verbose_name="Y轴列名",
            ),
        ),
        migrations.AddField(
            model_name="plotdata",
            name="y_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Y轴的单位，如"μH/m"',
                max_length=50,
                verbose_name="Y轴单位",
            ),
        ),
    ]
