# Generated by Django 4.2.11 on 2026-04-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="样品类型名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="样品类型描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_types",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "样品类型",
                "verbose_name_plural": "样品类型",
                "db_table": "sample_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "sample_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="样品编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="样品名称"
                    ),
                ),
                (
                    "material_abbreviation",
                    models.CharField(
                        help_text="用于生成样品编号", max_length=20, verbose_name="材料缩写"
                    ),
                ),
                (
                    "preparation_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="完全自由的键值对，每个样品可以完全不同",
                        verbose_name="制备条件",
                    ),
                ),
                (
                    "synthesis_date",
                    models.DateField(blank=True, null=True, verbose_name="合成日期"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="批次号"
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="用于标记样品状态",
                        max_length=100,
                        verbose_name="标记",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="samples.sampletype",
                        verbose_name="所属样品类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "样品",
                "verbose_name_plural": "样品",
                "db_table": "samples",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="sampletype",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_sample_type"
            ),
        ),
    ]
