# Generated by Django 4.2.11 on 2026-05-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_sample_display_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='preparation_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='瀹屽叏鑷\ue046敱鐨勯敭鍊煎\ue1ee锛屾瘡涓\ue045牱鍝佸彲浠ュ畬鍏ㄤ笉鍚?', verbose_name='制备条件'),
        ),
    ]
